### PR TITLE
Add BDD tests

### PR DESCRIPTION
**Pull request by rsajulga-nmdp**
Adding BDD (Behavior-driven development) tests for
- existing unit tests

  - [x]  No MAC
  - [x] MAC
  - [x] GLStrings

- new development
  - [x] https://github.com/nmdp-bioinformatics/py-ard/pull/46
  - [x] https://github.com/nmdp-bioinformatics/py-ard/pull/47

### CODE REVIEW

**Comment by rsajulga-nmdp** [comment]
Any idea @pbashyal-nmdp, @mmaiers-nmdp, etc. why `ard.redux_gl("HLA-A*01:AB", 'G')` does not produce any results when I run it through behave? For comparison, `ard.redux("HLA-A*01:01:01", 'G')` actually does produce the right result `'HLA-A*01:01:01G'`.

**Comment by pbashyal-nmdp** [comment]
Maybe related to `HLA-A` prefix bug that I fixed with PR #49

**Comment by mmaiers-nmdp** [comment]
There is definitely some odd behavior with regard to leading HLA-A

```ard.redux:    A*01:AB            , G = 
ard.redux_gl: A*01:AB            , G = A*01:01:01G/A*01:02
ard.redux:    A*01:01:01         , G = A*01:01:01G
ard.redux_gl: A*01:01:01         , G = A*01:01:01G
ard.redux:    HLA-A*01:AB        , G = HLA-
ard.redux_gl: HLA-A*01:AB        , G = 
ard.redux:    HLA-A*01:01:01     , G = HLA-A*01:01:01G
ard.redux_gl: HLA-A*01:01:01     , G = 
ard.redux:    DRB1*14:06:01      , G = DRB1*14:06:01
ard.redux_gl: DRB1*14:06:01      , G = DRB1*14:06:01
ard.redux:    DRB1*14:06:02      , G = DRB1*14:06:02
ard.redux_gl: DRB1*14:06:02      , G = DRB1*14:06:02
ard.redux:    A*01:AB            , lgx = A*01:AB
ard.redux_gl: A*01:AB            , lgx = A*01:01/A*01:02
ard.redux:    A*01:01:01         , lgx = A*01:01
ard.redux_gl: A*01:01:01         , lgx = A*01:01
ard.redux:    HLA-A*01:AB        , lgx = HLA-A*01:AB
ard.redux_gl: HLA-A*01:AB        , lgx = 
ard.redux:    HLA-A*01:01:01     , lgx = HLA-A*01:01
ard.redux_gl: HLA-A*01:01:01     , lgx = 
ard.redux:    DRB1*14:06:01      , lgx = DRB1*14:06
ard.redux_gl: DRB1*14:06:01      , lgx = DRB1*14:06
ard.redux:    DRB1*14:06:02      , lgx = DRB1*14:06
ard.redux_gl: DRB1*14:06:02      , lgx = DRB1*14:06
```

**Comment by mmaiers-nmdp** [comment]
Its better with 0.0.21

```
ard.redux:    A*01:AB            , G = 
ard.redux_gl: A*01:AB            , G = A*01:01:01G/A*01:02
ard.redux:    A*01:01:01         , G = A*01:01:01G
ard.redux_gl: A*01:01:01         , G = A*01:01:01G
ard.redux:    HLA-A*01:AB        , G = HLA-
ard.redux_gl: HLA-A*01:AB        , G = HLA-A*01:01:01G/HLA-A*01:02
ard.redux:    HLA-A*01:01:01     , G = HLA-A*01:01:01G
ard.redux_gl: HLA-A*01:01:01     , G = HLA-A*01:01:01G
ard.redux:    DRB1*14:06:01      , G = DRB1*14:06:01
ard.redux_gl: DRB1*14:06:01      , G = DRB1*14:06:01
ard.redux:    DRB1*14:06:02      , G = DRB1*14:06:02
ard.redux_gl: DRB1*14:06:02      , G = DRB1*14:06:02
ard.redux:    A*01:AB            , lgx = A*01:AB
ard.redux_gl: A*01:AB            , lgx = A*01:01/A*01:02
ard.redux:    A*01:01:01         , lgx = A*01:01
ard.redux_gl: A*01:01:01         , lgx = A*01:01
ard.redux:    HLA-A*01:AB        , lgx = HLA-A*01:AB
ard.redux_gl: HLA-A*01:AB        , lgx = HLA-A*01:01/HLA-A*01:02
ard.redux:    HLA-A*01:01:01     , lgx = HLA-A*01:01
ard.redux_gl: HLA-A*01:01:01     , lgx = HLA-A*01:01
ard.redux:    DRB1*14:06:01      , lgx = DRB1*14:06
ard.redux_gl: DRB1*14:06:01      , lgx = DRB1*14:06
ard.redux:    DRB1*14:06:02      , lgx = DRB1*14:06
ard.redux_gl: DRB1*14:06:02      , lgx = DRB1*14:06
```

**Comment by pbashyal-nmdp** [comment]
`ard.redux` only works on alleles, not on allele codes. Since `A*01:AB` is not a valid allele, it returns `''`
But you can pass in `remove_invalid=False` to return the original.

```
>>> ard = ARD('3290', data_dir='/tmp/3290', remove_invalid=False)
>>> ard.redux("HLA-A*01:AB", "G")
'HLA-A*01:AB'
```

Yeah, we definitely need to work on the spec of what it should do :)

**Comment by pbashyal-nmdp** [comment]
Created #51 to track the inconsistencies.

**Comment by mmaiers-nmdp** [comment]
after installing 0.0.22
```
ard.redux:    A*01:AB            , G = 
ard.redux_gl: A*01:AB            , G = A*01:01:01G/A*01:02
ard.redux:    A*01:01:01         , G = A*01:01:01G
ard.redux_gl: A*01:01:01         , G = A*01:01:01G
ard.redux:    HLA-A*01:AB        , G = 
ard.redux_gl: HLA-A*01:AB        , G = HLA-A*01:01:01G/HLA-A*01:02
ard.redux:    HLA-A*01:01:01     , G = HLA-A*01:01:01G
ard.redux_gl: HLA-A*01:01:01     , G = HLA-A*01:01:01G
ard.redux:    DRB1*14:06:01      , G = DRB1*14:06:01
ard.redux_gl: DRB1*14:06:01      , G = DRB1*14:06:01
ard.redux:    DRB1*14:06:02      , G = DRB1*14:06:02
ard.redux_gl: DRB1*14:06:02      , G = DRB1*14:06:02
ard.redux:    A*01:AB            , lgx = A*01:AB
ard.redux_gl: A*01:AB            , lgx = A*01:01/A*01:02
ard.redux:    A*01:01:01         , lgx = A*01:01
ard.redux_gl: A*01:01:01         , lgx = A*01:01
ard.redux:    HLA-A*01:AB        , lgx = HLA-A*01:AB
ard.redux_gl: HLA-A*01:AB        , lgx = HLA-A*01:01/HLA-A*01:02
ard.redux:    HLA-A*01:01:01     , lgx = HLA-A*01:01
ard.redux_gl: HLA-A*01:01:01     , lgx = HLA-A*01:01
ard.redux:    DRB1*14:06:01      , lgx = DRB1*14:06
ard.redux_gl: DRB1*14:06:01      , lgx = DRB1*14:06
ard.redux:    DRB1*14:06:02      , lgx = DRB1*14:06
ard.redux_gl: DRB1*14:06:02      , lgx = DRB1*14:06```

**Comment by rsajulga-nmdp** [comment]
Ah. Thank you @pbashyal-nmdp and @mmaiers-nmdp ! I forgot to set an upstream repository (I was pulling from my outdated fork). It works now!

**Comment by rsajulga-nmdp** [comment]
Should we be using a virtual environment for BDD testing? And should we put testing documentation in README.rst?

**Comment by pbashyal-nmdp** [comment]
Yes. 

Yes. Under a **Testing** heading.

**Comment by rsajulga-nmdp** [comment]
Okay, documentation for creating a virtual environment and running **behave** are added.

**Pull request merged**
