### PR TITLE
Remove Unbounded Cache

### PR DESCRIPTION
**Pull request by pbashyal-nmdp**
- The LRU cache was unbounded and is problematic when used in long running services. Set it to 1000.
 - Use raw strings for regex characters
 - General cleanup

### CODE REVIEW

**Review by mmaiers-nmdp — APPROVED** [review]
Yes.  Looks good to me.

**Comment by mmaiers-nmdp** [comment]
Have you done any timings on the performance with the cache limit?  i can't imagine its a major hit.

**Comment by bashyal** [comment]
It'll help with performance but letting it be unbounded in terms of the cache size will balloon memory usage.

**Comment by pbashyal-nmdp** [comment]
It'll help with performance but letting it be unbounded in terms of the cache size will balloon memory usage in long running services that include pyard as a dependency.

**Pull request merged**
