### PR TITLE
Predict v3 from v2

### PR DESCRIPTION
**Pull request by pbashyal-nmdp**
-  Heuristically predict V3 from V2 when not in exceptional case list
-  Make `is_XX` a public method on the ARD object
- Update README and fix bug in `pyard-import` for importing into Latest

### CODE REVIEW

**Review by mmaiers-nmdp — APPROVED** [review]
LGTM.  Has this been tested against something like Nomenclature2010.pm?

**Comment by pbashyal-nmdp** [comment]
No, I haven't. This is based on MG's Java code.

**Comment by mmaiers-nmdp** [comment]
> No, I haven't. This is based on MG's Java code.

That can be an exercise for the reader.

**Comment by pbashyal-nmdp** [comment]
I looked through `Nomenclature2010.pm` which seems to just look up the mapping in the database. This method copies the logic that's used to create the mapping.

**Pull request merged**
